### ISSUE TITLE
Re-render on browser resize

### ISSUE THREAD

**Issue by mbodge** [borisyankov/react-sparklines#11]
First of all, thank you so much for the library. It's been invaluable in this project I'm working on. Thanks thanks.

I'm looking to have the sparkline be the entire width of the browser. The issue is when someone resizes the browser I have a function that is called that does a forceUpdate() on the React component. This doesn't re-render the component to the new div width. Only updating the data does that. 

Any ideas?

**Comment by borisyankov** [comment]
shouldComponentUpdate() is the culprit. It causes a rerender only when the data changes. 
Need to improve it to do so on any property change.

**Comment by mbodge** [comment]
gotcha, so I’m guessing there’s no hacky trick I can do in the meantime?

**Comment by borisyankov** [comment]
Cool thing about React is, good solutions are usually easy to do.
I'll try to fix this today.
If you want to experiment, go to your node_modules folder find react-sparklines, open the .js file and remove the shouldComponentUpdate() and see if it works.

**Comment by borisyankov** [comment]
I published a new version, please try it out.

**Comment by mbodge** [comment]
Hey Boris, thanks for looking into this. I've updated the files but it still doesn't update on resize. 

```
var HeaderStats = React.createClass({
  getInitialState: function() {
      return {stats: []};
  },
  reRender: function(){
    this.forceUpdate();
  },
  componentWillMount: function() {
      window.addEventListener("resize", this.reRender);
  },
    render: function() {

        var headerHeight = document.getElementById('header').offsetHeight;
        var headerWidth = document.getElementById("header").offsetWidth;

        return(

          <Sparklines data={this.state.stats} width={headerWidth} height={headerHeight}>
            <SparklinesLine style={{ stroke: "#f00", fill: "none"}} />
            <SparklinesSpots size={0} style={{ stroke: "#f00", strokeWidth: 3, fill: "black" }} />
            <SparklinesReferenceLine type="mean" />
          </Sparklines>

        )

    }
});
```

**Comment by mbodge** [comment]
Actually sorry, getting an error now within sparklines:

```
Uncaught TypeError: Cannot read property 'width' of nullshouldComponentUpdate @ index.js:143
```

which is:

```
 _createClass(Sparklines, [{
	        key: 'shouldComponentUpdate',
	        value: function shouldComponentUpdate(nextProps, nextState) {
	            var _this = this;

	            return nextProps.width != nextState.width || nextProps.height != nextState.height || nextProps.margin != nextState.margin || nextProps.data.some(function (d, i) {
	                return d !== _this.props.data[i];
	            });
	        }
	    }

```

**Comment by okonet** [comment]
@mbodge this is a separate issue #12 which is now fixed by #13 Please update to the latest version from npm.
